name: Build Android APK with Buildozer

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install essential system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            autopoint \
            libltdl-dev \
            ccache \
            python3-pip \
            python3-setuptools

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk
          mkdir -p ~/.buildozer/android/platform/android-ndk

          # Download Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q commandlinetools-linux-8512546_latest.zip
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          mv cmdline-tools/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools commandlinetools-linux-8512546_latest.zip

          # Download Android NDK
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          mv android-ndk-r25b/* ~/.buildozer/android/platform/android-ndk/
          rm -rf android-ndk-r25b android-ndk-r25b-linux.zip

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            # Update buildozer.spec with our settings
            sed -i 's/^title = .*/title = Exam App/' buildozer.spec
            sed -i 's/^package.name = .*/package.name = examapp/' buildozer.spec
            sed -i 's/^package.domain = .*/package.domain = org.exam/' buildozer.spec
            sed -i 's/^orientation = .*/orientation = portrait/' buildozer.spec
            sed -i 's/^android.api = .*/android.api = 33/' buildozer.spec
            sed -i 's/^android.ndk = .*/android.ndk = 25b/' buildozer.spec
            sed -i 's/^android.permissions = .*/android.permissions = INTERNET/' buildozer.spec
          fi

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk