name: Build Android APK with Kivy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: kivy/android-apk-generator@v1.3.0
        with:
          package-name: org.exam.examapp
          app-name: Exam App
          version: 0.1
          orientation: portrait
          requirements: kivy
          main-file: main.py  # Убедитесь, что у вас есть main.py в корне проекта
          icon-path: icon.png  # Опционально: путь к иконке приложения
          presplash-path: presplash.png  # Опционально: путь к заставке при запуске
          permissions: INTERNET

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/*.apk