name: Build Android APK with Python-for-Android

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Используем Python 3.8 для лучшей совместимости

      - name: Install essential system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            autopoint \
            libltdl-dev \
            ccache

      - name: Install Python-for-Android and Cython
        run: |
          pip install python-for-android==2020.3.30  # Стабильная версия
          pip install cython==0.29.21  # Совместимая версия Cython

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p android-sdk
          mkdir -p android-ndk

          # Скачиваем Android Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
          unzip -q commandlinetools-linux-6200805_latest.zip
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools commandlinetools-linux-6200805_latest.zip

          # Используем NDK r19c для лучшей совместимости с python-for-android
          wget -q https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip
          unzip -q android-ndk-r19c-linux-x86_64.zip
          mv android-ndk-r19c/* android-ndk/
          rm -rf android-ndk-r19c android-ndk-r19c-linux-x86_64.zip

          echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$GITHUB_WORKSPACE/android-ndk:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses

      - name: Install Android platform and build-tools
        run: |
          sdkmanager "platforms;android-28"  # Android 9.0 (Pie)
          sdkmanager "build-tools;28.0.3"
          sdkmanager "platform-tools"

      - name: Build with Python-for-Android
        run: |
          # Создаем простой main.py если его нет
          if [ ! -f main.py ]; then
            echo "print('Hello from Exam App')" > main.py
          fi

          p4a apk \
            --dist_name=examapp \
            --bootstrap=sdl2 \
            --requirements=python3,kivy==2.0.0 \  # Стабильная версия Kivy
            --arch=arm64-v8a \
            --android-api=28 \
            --private=. \
            --package=org.exam.examapp \
            --name="Exam App" \
            --version=0.1 \
            --orientation=portrait \
            --window \
            --permission=INTERNET

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/*.apk