name: Build Android APK with Kivy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        uses: kivy/android-apk-generator@master
        with:
          package-name: org.exam.examapp
          app-name: Exam App
          version: 0.1
          orientation: portrait
          requirements: kivy
          main-file: main.py
          permissions: INTERNET

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/*.apk