name: Build Android APK with Python-for-Android in Docker

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build using Python-for-Android in Docker
        run: |
          # Создаем простой main.py если его нет
          if [ ! -f main.py ]; then
            echo "print('Hello from Exam App')" > main.py
          fi

          # Запускаем сборку в контейнере с python-for-android
          docker run --rm \
            -v $PWD:/src \
            -v $PWD/.python-for-android:/root/.local/share/python-for-android \
            python:3.8-slim-bullseye \
            bash -c "
            cd /src &&
            apt-get update &&
            apt-get install -y \
                git \
                zip \
                unzip \
                openjdk-8-jdk \
                autoconf \
                automake \
                libtool \
                pkg-config \
                zlib1g-dev \
                cmake \
                libffi-dev \
                libssl-dev \
                python3-pip \
                python3-setuptools &&
            pip install python-for-android &&
            p4a apk \
                --dist_name=examapp \
                --bootstrap=sdl2 \
                --requirements=python3,kivy \
                --arch=arm64-v8a \
                --android-api=33 \
                --private=. \
                --package=org.exam.examapp \
                --name='Exam App' \
                --version=0.1 \
                --orientation=portrait \
                --window \
                --permission=INTERNET
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/*.apk