name: Build Android APK with Kivy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            cp buildozer-spec-template.txt buildozer.spec
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build using Ubuntu Docker image
        run: |
          # Запускаем сборку в Ubuntu 20.04 контейнере
          docker run --rm \
            -v $PWD:/src \
            -v $PWD/.buildozer:/root/.buildozer \
            ubuntu:20.04 \
            bash -c "
            # Устанавливаем переменные окружения для автоматической конфигурации tzdata
            export DEBIAN_FRONTEND=noninteractive
            export TZ=Europe/Moscow

            # Настройка локали для избежания предупреждений
            apt-get update && apt-get install -y locales tzdata
            ln -fs /usr/share/zoneinfo/\$TZ /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata
            locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            export LANGUAGE=en_US:en
            export LC_ALL=en_US.UTF-8

            # Установка зависимостей
            apt-get update && apt-get install -y \
                software-properties-common \
                git \
                zip \
                unzip \
                openjdk-8-jdk \
                autoconf \
                automake \
                libtool \
                pkg-config \
                zlib1g-dev \
                cmake \
                libffi-dev \
                libssl-dev \
                gettext \
                autopoint \
                libltdl-dev \
                ccache \
                python3 \
                python3-pip \
                python3-setuptools \
                wget

            # Установка Buildozer
            pip3 install --upgrade pip
            pip3 install buildozer cython

            # Переходим в директорию проекта и запускаем сборку
            cd /src
            
            # Запускаем сборку
            buildozer android debug
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk