name: Build Android APK with Kivy

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            cp buildozer-spec-template.txt buildozer.spec
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install Android SDK components
        run: |
          # Создание каталога для Android SDK
          mkdir ~/android-sdk
          # Загрузка архива Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          # Распаковка архива
          unzip commandlinetools-linux-7583922_latest.zip -d ~/android-sdk
          # Перемещаем извлечённую директорию в нужное место
          mv ~/android-sdk/cmdline-tools ~/android-sdk/tools
          # Указываем корневую директорию SDK явно
          ANDROID_HOME=~/android-sdk
          export ANDROID_HOME
          # Соглашаемся с лицензиями
          yes | "$ANDROID_HOME"/tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --licenses
          # Установка необходимых компонентов
          "$ANDROID_HOME"/tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --install "build-tools;30.0.3" "platforms;android-30" "platform-tools"

      - name: Install minimal dependencies
        run: |
          # Установка минимального набора зависимостей
          sudo apt-get update && sudo apt-get install -y ...

          # Установка Python 3 и pip
          sudo apt-get install -y python3 python3-pip python3-setuptools

          # Установка Buildozer
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build Android APK inside Docker container
        run: |
          # Запускаем сборку в Ubuntu 20.04 контейнере
          docker run --rm \
            -v $PWD:/src \
            -v $PWD/.buildozer:/root/.buildozer \
            ubuntu:20.04 \
            bash -c "
            # Настройка локали
            apt-get update && apt-get install -y locales tzdata
            locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            export LANGUAGE=en_US:en
            export LC_ALL=en_US.UTF-8

            # Установка временных зон
            ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata

            # Переход в рабочую директорию и запуск сборки
            cd /src
            BUILDOZER_ANDROID_SDK=$HOME/android-sdk BUILDOZER_ANDROID_NDK=/opt/android-ndk-r25b buildozer --no-input android debug
            "

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk