name: Build Android APK with Python-for-Android

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install essential system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            gettext \
            autopoint \
            libltdl-dev \
            ccache

      - name: Install Python-for-Android and Cython
        run: |
          pip install --upgrade python-for-android
          pip install cython==0.29.33

      - name: Set up Android SDK and NDK
        run: |
          mkdir -p android-sdk
          mkdir -p android-ndk

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q commandlinetools-linux-8512546_latest.zip
          mkdir -p android-sdk/cmdline-tools/latest
          mv cmdline-tools/* android-sdk/cmdline-tools/latest/
          rm -rf cmdline-tools commandlinetools-linux-8512546_latest.zip

          # Используем рекомендуемую версию NDK 25b
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          mv android-ndk-r25b/* android-ndk/
          rm -rf android-ndk-r25b android-ndk-r25b-linux.zip

          echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk" >> $GITHUB_ENV
          echo "PATH=$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin:$GITHUB_WORKSPACE/android-ndk:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses

      - name: Install Android platform and build-tools
        run: |
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.0"
          sdkmanager "platform-tools"
          sdkmanager "cmake;3.22.1"

      - name: Remove problematic Python 2 scripts from NDK
        run: |
          # Удаляем все проблемные Python 2 скрипты из NDK
          find "$ANDROID_NDK_HOME" -name "*.py" -exec grep -l "print [^']" {} \; | xargs rm -f || true
          find "$ANDROID_NDK_HOME" -name "*.py" -exec grep -l "print '" {} \; | xargs rm -f || true

      - name: Create custom recipes
        run: |
          mkdir -p recipes/pyjnius
          cat > recipes/pyjnius/__init__.py << EOF
          from pythonforandroid.recipes.pyjnius import PyjniusRecipe

          class PyJniusRecipe(PyjniusRecipe):
            version = 'master'
            url = 'https://github.com/kivy/pyjnius/archive/master.zip'

          recipe = PyJniusRecipe()
          EOF

          mkdir -p recipes/kivy
          cat > recipes/kivy/__init__.py << EOF
          from pythonforandroid.recipes.kivy import KivyRecipe
          import os
          import shutil

          class KivyRecipeFixed(KivyRecipe):
            # Используем более новую версию Kivy, совместимую с NDK 25
            version = '2.3.0'
            url = 'https://github.com/kivy/kivy/archive/refs/tags/2.3.0.zip'

            def prebuild_arch(self, arch):
                super().prebuild_arch(arch)
                # Удаляем проблемные C++ файлы, которые не нужны для Android
                build_dir = self.get_build_dir(arch.arch)
                problematic_files = [
                    os.path.join(build_dir, 'kivy', 'graphics', 'egl_backend', 'egl_angle_metal.pyx'),
                    os.path.join(build_dir, 'kivy', 'graphics', 'egl_backend', 'egl_angle_metal.pxd'),
                    os.path.join(build_dir, 'kivy', 'graphics', 'egl_backend', 'egl_angle_metal.cpp')
                ]
                
                for file_path in problematic_files:
                    if os.path.exists(file_path):
                        print(f"Removing problematic file: {file_path}")
                        os.remove(file_path)

          recipe = KivyRecipeFixed()
          EOF

      - name: Build with Python-for-Android
        run: |
          p4a apk \
            --dist_name=examapp \
            --bootstrap=sdl2 \
            --requirements=python3,kivy \
            --arch=arm64-v8a \
            --android-api=33 \
            --private=. \
            --package=org.exam.examapp \
            --name="Exam App" \
            --version=0.1 \
            --orientation=portrait \
            --window \
            --permission=INTERNET \
            --local-recipes=recipes \
            --ndk-api=21

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/*.apk